### ISSUE TITLE
openstack-lxd bundle places control services in lxd containers on nova-lxd nodes, which is buggy

### ISSUE THREAD

**Issue by jhobbs** [openstack-charmers/openstack-bundles#18]
21:10 < jhobbs> rockstar: do we need to avoid putting nova-lxd compute nodes on on the same system as juju managed lxd containers?
21:11 < jhobbs> zul: ^^ 
21:11 < rockstar> jhobbs: there is a bug, currently, where if you put the control plane in lxd containers, and then try to but compute nodes on the same system, the configuring of nova-lxd breaks some things.
21:12 < jhobbs> ok
21:12 < rockstar> This is a well-known bug, and one that we probably need to find some time to address.

**Comment by ryan-beisner** [comment]
This bundle originated with Juju 1 (lxc), where this conflict wasn't an issue.  There are a number of things that should probably happen, starting with:

1. Updating the charm store bundle to not co-locate services with the nova-lxd compute nodes for now, so that the published bundle works with Juju 2 and nova-lxd as they exist today; and

2. Raise (or confirm if it exists) a LP bug to track the underlying issue, which is a tug-of-war of the lxd storage configuration between Juju and nova-lxd.

**Comment by jhobbs** [comment]
Here's the bug against nova-lxd https://bugs.launchpad.net/nova-lxd/+bug/1661762
