### ISSUE TITLE
Communication between virtual and physical network does not seem to work "Openstack Base Bundle" does not work Edit

### ISSUE THREAD

**Issue by javacruft** [openstack-charmers/openstack-bundles#7]
Taken from: https://bugs.launchpad.net/juju/+bug/1639792

When using the default parameters of the "Openstack Base Bundle", the deployment is successful.
We have a full deployment with the default number of node (4).
Once in Horizon (openstack-dashboard), VM (instances) associated to the tenant "admin" can be added.
Those instances were created with ubuntu qcow2 image (trusty-server-cloudimg-amd64-disk1.img).

In "Access & Security" TCP, UDP and ICMP have been fully open.

In "Network", a local network for tenant (with DHCP) and the external network (giving internet access) were added.
A router to make the transition between the two networks was also created.

All the networks are up as well as the router with its interfaces.

Console of the instances is not accessible and it is not possible to ping the external interface of the router even though it as an IP.

This is not my first Openstack deployment but it is my first deployment using Ubuntu server as deployment server (MAAS+Juju). It looks suspiciously like a problem that would be in the bundle default settings and prevent the neutron network to interact with the physical interfaces of the system. A colleague of mine had the exact same results trying a similar setup on his own hardware.

**Comment by javacruft** [comment]
OK - so as the router itself is not contactable, this would indicate some sort of network configuration issue on the machine hosting the neutron-gateway unit; by default the bundle binds the 'external' network port for north/south traffic routing to eth1 on the machine - this will need to be appropriately cabled to the correct underlying network segment to ensure accessibility to the router and instances.

Can you confirm that this is the case?  A good debug step is to ssh to the neutron-gateway unit, and using the ip netns command to drop into the router namespace and check whether it can ping its default gateway for the external network configuration.

**Comment by lathiat** [comment]
The cause for this issue was needing to adjust data-port=br-ex:eth1 within the bundle.  For deploys on xenial, the network interfaces are not by default labelled eth1.

The fix is to either update this setting, or alternatively (but perhaps not the best practice) set global boot options in MAAS to net.ifnames=0

We should probably improve the README.md to this effect, on trusty or xenial with legacy interface names it often works by "accident" in that usually there are only 2 interfaces and eth1 is the correct interface.  As part of the network setup.
